package huayang.hychat.model.po;

import java.io.Serializable;

public class ChatFriend implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_friend.friend_flow
     *
     * @mbggenerated
     */
    private String friendFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_friend.origin_user_flow
     *
     * @mbggenerated
     */
    private String originUserFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_friend.target_user_flow
     *
     * @mbggenerated
     */
    private String targetUserFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_friend.friend_flow
     *
     * @return the value of chat_friend.friend_flow
     *
     * @mbggenerated
     */
    public String getFriendFlow() {
        return friendFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_friend.friend_flow
     *
     * @param friendFlow the value for chat_friend.friend_flow
     *
     * @mbggenerated
     */
    public void setFriendFlow(String friendFlow) {
        this.friendFlow = friendFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_friend.origin_user_flow
     *
     * @return the value of chat_friend.origin_user_flow
     *
     * @mbggenerated
     */
    public String getOriginUserFlow() {
        return originUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_friend.origin_user_flow
     *
     * @param originUserFlow the value for chat_friend.origin_user_flow
     *
     * @mbggenerated
     */
    public void setOriginUserFlow(String originUserFlow) {
        this.originUserFlow = originUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_friend.target_user_flow
     *
     * @return the value of chat_friend.target_user_flow
     *
     * @mbggenerated
     */
    public String getTargetUserFlow() {
        return targetUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_friend.target_user_flow
     *
     * @param targetUserFlow the value for chat_friend.target_user_flow
     *
     * @mbggenerated
     */
    public void setTargetUserFlow(String targetUserFlow) {
        this.targetUserFlow = targetUserFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChatFriend other = (ChatFriend) that;
        return (this.getFriendFlow() == null ? other.getFriendFlow() == null : this.getFriendFlow().equals(other.getFriendFlow()))
            && (this.getOriginUserFlow() == null ? other.getOriginUserFlow() == null : this.getOriginUserFlow().equals(other.getOriginUserFlow()))
            && (this.getTargetUserFlow() == null ? other.getTargetUserFlow() == null : this.getTargetUserFlow().equals(other.getTargetUserFlow()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFriendFlow() == null) ? 0 : getFriendFlow().hashCode());
        result = prime * result + ((getOriginUserFlow() == null) ? 0 : getOriginUserFlow().hashCode());
        result = prime * result + ((getTargetUserFlow() == null) ? 0 : getTargetUserFlow().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", friendFlow=").append(friendFlow);
        sb.append(", originUserFlow=").append(originUserFlow);
        sb.append(", targetUserFlow=").append(targetUserFlow);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}