package huayang.hychat.model.po;

import java.io.Serializable;

public class ChatUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.user_flow
     *
     * @mbggenerated
     */
    private String userFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.user_code
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.user_pwd
     *
     * @mbggenerated
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.user_flow
     *
     * @return the value of chat_user.user_flow
     *
     * @mbggenerated
     */
    public String getUserFlow() {
        return userFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.user_flow
     *
     * @param userFlow the value for chat_user.user_flow
     *
     * @mbggenerated
     */
    public void setUserFlow(String userFlow) {
        this.userFlow = userFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.user_code
     *
     * @return the value of chat_user.user_code
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.user_code
     *
     * @param userCode the value for chat_user.user_code
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.user_pwd
     *
     * @return the value of chat_user.user_pwd
     *
     * @mbggenerated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.user_pwd
     *
     * @param userPwd the value for chat_user.user_pwd
     *
     * @mbggenerated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.user_name
     *
     * @return the value of chat_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.user_name
     *
     * @param userName the value for chat_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChatUser other = (ChatUser) that;
        return (this.getUserFlow() == null ? other.getUserFlow() == null : this.getUserFlow().equals(other.getUserFlow()))
            && (this.getUserCode() == null ? other.getUserCode() == null : this.getUserCode().equals(other.getUserCode()))
            && (this.getUserPwd() == null ? other.getUserPwd() == null : this.getUserPwd().equals(other.getUserPwd()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserFlow() == null) ? 0 : getUserFlow().hashCode());
        result = prime * result + ((getUserCode() == null) ? 0 : getUserCode().hashCode());
        result = prime * result + ((getUserPwd() == null) ? 0 : getUserPwd().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userFlow=").append(userFlow);
        sb.append(", userCode=").append(userCode);
        sb.append(", userPwd=").append(userPwd);
        sb.append(", userName=").append(userName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}