package huayang.hychat.dao.base;

import huayang.hychat.model.po.ChatUser;
import huayang.hychat.model.po.ChatUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    int countByExample(ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    int deleteByExample(ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userFlow);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    int insert(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    int insertSelective(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    List<ChatUser> selectByExample(ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    ChatUser selectByPrimaryKey(String userFlow);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChatUser record, @Param("example") ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChatUser record, @Param("example") ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChatUser record);
}