package huayang.hychat.dao.base;

import huayang.hychat.model.po.ChatFriend;
import huayang.hychat.model.po.ChatFriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    int countByExample(ChatFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    int deleteByExample(ChatFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String friendFlow);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    int insert(ChatFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    int insertSelective(ChatFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    List<ChatFriend> selectByExample(ChatFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    ChatFriend selectByPrimaryKey(String friendFlow);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChatFriend record, @Param("example") ChatFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChatFriend record, @Param("example") ChatFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChatFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_friend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChatFriend record);
}